### ISSUE TITLE
Can someone help me in this discord bot? how to fix this

### ISSUE THREAD

**Issue by navirogerg** [StephanAkkerman/Axie_Manager_Bot#137]
Everytime I use command I always get this spam error

![image](https://user-images.githubusercontent.com/96023410/145798675-c35a6371-c678-4a3b-a249-c82a8de3c9f6.png)

![image](https://user-images.githubusercontent.com/96023410/145798909-77ed17bb-57e1-4e1f-a14c-7b2d657bc527.png)

**Comment by navirogerg** [comment]
How to fix this error ?

Command raised an exception: HTTPException: 429 Too Many Requests (error code: 0): You are being rate limited.

**Comment by StephanAkkerman** [comment]
@navirogerg I have replied to your email, sorry the readme is outdated and will soon be updated, but writing it takes a lot of time and effort

**Comment by navirogerg** [comment]
thank you for responding to my request

can you help me a little bit? if you only have a moment

i already setup your v2 on my discord server, but somehow i've getting this
error, and whenever i use a command always spamming me, also it said i
don't have permission?
sorry i'm not professional using python this is my first time, but i have
some knowledge on programming so i can understand your instructions

by the way your work is so amazing, i love it!

[image: image.png]
