### ISSUE TITLE
Improve comment on Source Code

### ISSUE THREAD

**Issue by igmtOfficial** [StephanAkkerman/Axie_Manager_Bot#144]
Can you add also each code or what i mean is each function code add a comment if what use that code, for your fan a newbie on coding like me so i can understand all your code.

Example:
// Reaction Role // -- Comment
          -- Code here

**Comment by StephanAkkerman** [comment]
@navirogerg In the final project release I will improve the README and config_example.yaml to explain in detail what each part of the bot does, so everyone knows if they want to disable or enable this

**Comment by navirogerg** [comment]
good to hear that, i can't wait

**Comment by StephanAkkerman** [comment]
Should be good for now
