### ISSUE TITLE
Automated send scholar quotation status if they hit their quotation in specific channel

### ISSUE THREAD

**Issue by igmtOfficial** [StephanAkkerman/Axie_Manager_Bot#152]
This will be the format

![image](https://user-images.githubusercontent.com/96023410/146572334-fa524584-5c1f-4eec-b876-a70b57f07199.png)

https://tracker.axie.management/

![image](https://user-images.githubusercontent.com/96023410/146572014-0267b224-02d4-4b15-ad82-a295d89f100c.png)

**Comment by StephanAkkerman** [comment]
As discussed on discord it is better to send a scholar a message if they did not yet do this, so they won't be uncouraged to stop playing
