### ISSUE TITLE
I don't have permission to use this commands.

### ISSUE THREAD

**Issue by ProfligateMoney** [StephanAkkerman/Axie_Manager_Bot#171]
I'm sure I missed something because I can't use manager commands and after I try I get a DM from my own bot saying:
"Sorry, you do not have permission to use this command. Please contact a manager if you think that you should."

Hopefully, you can help me with this issue.
Have a good one.

**Comment by StephanAkkerman** [comment]
@ProfligateMoney Do you have the manager role in your server?

**Comment by ProfligateMoney** [comment]
@StephanAkkerman It seemed like a bug, I changed the role name and saved the file but it wouldn't recognize it in the server.
Had to redo the config.yaml file with new names and it worked! Thanks

**Comment by ProfligateMoney** [comment]
When I try to add my scholar the following message appears: "Sorry, the new scholar does not yet have the role Verified. Ask them to verify themselves first."
I got the message in the command prompt after he reacted to the emoji, so he is verified. Even checked it manually and was assigned that role.

Also, I'm having some issues while trying to set it in my VPS or in my Raspberry Pi, whenever I run the command I get the following message:
"File "src/main.py", line 21
    async def on_ready():
        ^
SyntaxError: invalid syntax"

**Comment by StephanAkkerman** [comment]
@ProfligateMoney I am working on that for version V4, you can check the development in the project section
