### ISSUE TITLE
create debug mode

### ISSUE THREAD

**Issue by TimKoornstra** [StephanAkkerman/Axie_Manager_Bot#35]
example:
![afbeelding](https://user-images.githubusercontent.com/89044870/137909732-1983ff85-413f-4056-b6ce-2bb0943dbb1b.png)
could also use logging?

**Comment by StephanAkkerman** [comment]
https://stackoverflow.com/questions/1593274/how-do-i-check-if-the-python-debug-option-is-set-from-within-a-script

**Comment by StephanAkkerman** [comment]
This could also replace -test

**Comment by StephanAkkerman** [comment]
https://stackoverflow.com/questions/13352677/python-equivalent-for-ifdef-debug/

**Comment by StephanAkkerman** [comment]
Can just use `if len(sys.argv) > 1 and sys.argv[1] == "-test"` instead of if __debug__
