### ISSUE TITLE
Send warning if a scholar's weekly average is below threshold

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/Axie_Manager_Bot#7]
For instance if our minimum is 100 SLP per day but weekly average of a scholar is below that.

Tasks:
- [ ] Send warning to scholar
- [ ] Notify managers (in channel)

**Comment by TimKoornstra** [comment]
- [ ] Send warning to scholar
- [ ] Notify managers (in channel)

**Comment by StephanAkkerman** [comment]
Forgot to close #7 in commit
