### ISSUE TITLE
Translate message function

### ISSUE THREAD

**Issue by TimKoornstra** [StephanAkkerman/Axie_Manager_Bot#86]
To translate from English to Tagalog and vice versa, for example
Alternatively: if bot reads a message in tagalog, it will translate it automatically

**Comment by StephanAkkerman** [comment]
Some libraries:
https://pypi.org/project/googletrans/
https://pypi.org/project/translate-api/
https://pypi.org/project/translate/

**Comment by StephanAkkerman** [comment]
Maybe have a special channel that will translate all tagalog messages and post them in there

**Comment by StephanAkkerman** [comment]
https://withwin.in/make-an-easy-python-bot-to-automatically-translate-discord-messages/

**Comment by StephanAkkerman** [comment]
Make this a listeners for every incoming message and check if it is tagalog (or any other language set in config)
