### ISSUE TITLE
Send a daily warning near the reset tagging scholars

### ISSUE THREAD

**Issue by TimKoornstra** [StephanAkkerman/Axie_Manager_Bot#91]
Right now it starts at the 14th of each month. That means that it could do nothing for an entire month...
Maybe this can be improved by starting it on a day that has % 7 = 0. So, 7, 14, 21, or 28 of each month

**Comment by StephanAkkerman** [comment]
Maybe do something like this: https://media.discordapp.net/attachments/893203608299012156/918591665114083378/unknown.png

**Comment by StephanAkkerman** [comment]
![image](https://user-images.githubusercontent.com/45365128/145898674-f75d2c2d-c52e-4eaa-9f1d-24d12bead678.png)
https://game-api.axie.technology/player/RONIN_ADDRESS
https://game-api.axie.technology/missions/RONIN_ADDRESS

**Comment by StephanAkkerman** [comment]
The daily reset is 00:00 UTC i think
